### ISSUE TITLE
toast-notifications inside modal.

### ISSUE THREAD

**Issue by franciscoSankhya** [arnnis/react-native-toast-notifications#102]
### Current behaviour

toastWarnings doesnt work inside Modal

### Expected behaviour

expected to work inside modal, not in parent component

### Code sample

running app via USB

**Comment by arnnis** [comment]
This is a duplicate of #50 and #85. The following FAQ may help [How to show toast inside a Modal?](https://github.com/arnnis/react-native-toast-notifications#--how-to-show-toast-inside-a-modal)

**Comment by carrie503** [comment]
I have written another workaroud so we can use `useToast`

See here:
https://github.com/arnnis/react-native-toast-notifications/issues/50#issuecomment-1637708341
