### ISSUE TITLE
Question: Using toast inside and outside react Component

### ISSUE THREAD

**Issue by ramiel1999** [arnnis/react-native-toast-notifications#117]
If I want to use the toast inside react components and also in a redux store should I wrap my app in ToastProvider or can I just use: 
```
import Toast from "react-native-toast-notifications";

export default function App() {
  return (
    <>
      <RestOfYourApp />
      <Toast ref={(ref) => global['toast'] = ref} />
    </>
  );
```

If I can use the above one in anywhere why should I wrap my app in ToastProvider? Are there any benefits

**Comment by arnnis** [comment]
Answered here:
https://github.com/arnnis/react-native-toast-notifications/discussions/105
