### ISSUE TITLE
Do we have center placement?

### ISSUE THREAD

**Issue by ardiansyaherwin** [arnnis/react-native-toast-notifications#120]
hi, love your works, do we have center placement for toast?

**Comment by xAgustin93** [comment]
I have created this PR to solve this problem
https://github.com/arnnis/react-native-toast-notifications/pull/135

**Comment by arnnis** [comment]
This is now supported in version [3.3.0](https://github.com/arnnis/react-native-toast-notifications/releases/tag/v3.3.0)
