### ISSUE TITLE
Infinite duration until closed? (feature request)

### ISSUE THREAD

**Issue by nikki-cat** [arnnis/react-native-toast-notifications#124]
Could it be possible to set an option to keep a toast open until closed manually?
It would be useful for toasts that are very important.

**Comment by arnnis** [comment]
This is already supported.
Use `duration: 0`. It wont close until you close it manually

**Comment by nikki-cat** [comment]
oh! I see 😅 That's awesome. Thank you for the reply.

**Comment by Sargnec** [comment]
> This is already supported. Use `duration: 0`. It wont close until you close it manually

This should be in readme. Thanks ✋🏼
