### ISSUE TITLE
typescript: Type '{ children: Element; }' has no properties in common with type 'IntrinsicAttributes & Props'.

### ISSUE THREAD

**Issue by ShivamJoker** [arnnis/react-native-toast-notifications#131]
### Current behaviour

Getting type error while wrapping provider

![image](https://user-images.githubusercontent.com/23727670/168022257-05185993-3f04-476c-b1cb-378d10f576b4.png)

### Expected behaviour

No TS error

### Your Environment

| software                         | version |
| -------------------------------- | ------- |
| ios or android                   | both
| react-native                     |0.65.2
| react-native-toast-notifications | 3.2.3
| node                             | 16
| npm or yarn                      | yarn

**Comment by AmeerHamoodi** [comment]
I had the same problem. See my PR https://github.com/arnnis/react-native-toast-notifications/pull/136. If you want to have these changes before the PR gets merged (if it does), check out patch-package (https://www.npmjs.com/package/patch-package). With it you can just implement changes to node_modules, and it persists it between installations

**Comment by arnnis** [comment]
This is fixed in the latest patch
