### ISSUE TITLE
A typescript error "not assignable" occured when use toast outside of react component

### ISSUE THREAD

**Issue by sgshy1995** [arnnis/react-native-toast-notifications#163]
### Current behaviour

I want to use Toast outside of  TypeScript React Component. I add Toast in root component of my app and add `index.d.ts` to my project root. But a ts error occured which prompts me not assignable.

I find that type of ref is `Toast | null`, but declare toast in the index.d.ts is `ToastType`. How can it works?

After I do something in index.d.ts, the ts error disappears but the syntax prompt disappears either.

### Expected behaviour

It can be used correctly in typescript outside of react component. 

### Code sample

```js
/* App.tsx */
import Toast from "react-native-toast-notifications";

const App = () => {

  return (
    <Provider store={store}>
      ...
      <Navigation />
      <Toast ref={(ref) => global['toast'] = ref} />
    </Provider>
  );
};

export default App;
```

```typescript
/* index.d.ts */
type ToastType = import("react-native-toast-notifications").ToastType;

declare global {
  const toast: Toas;
}

declare var toast: ToastType;
```

### Screenshots (if applicable)

<img width="1000" alt="image" src="https://user-images.githubusercontent.com/45568580/210921488-6fc1086d-24eb-4bda-a115-7d549123d182.png">

<img width="594" alt="image" src="https://user-images.githubusercontent.com/45568580/210921628-9d16a01f-1560-4063-ab1b-84ae97f9cb89.png">

<img width="207" alt="image" src="https://user-images.githubusercontent.com/45568580/210921414-af13973b-1e97-4984-ae99-fdd342f6dd4c.png">

### What have you tried

I try to change the type of toast, it seems like that the typescript error disappear but the syntax prompt disappears either.

```typescript
/* index.d.ts */
type ToastContainerType = import("react-native-toast-notifications/lib/typescript/toast-container");
//type ToastType = import("react-native-toast-notifications").ToastType;

declare global {
  const toast: ToastContainerType;
}

declare var toast: ToastContainerType;
```

<img width="691" alt="image" src="https://user-images.githubusercontent.com/45568580/210935847-abc010fa-3c09-4515-a1fb-1cc8ffc7f848.png">

### Your Environment

| software                         | version |
| -------------------------------- | ------- |
| ios                   |  15.2(iphone 13 simulator on macos Ventura 13.0.1)
| react-native                     |  0.68.2
| react-native-toast-notifications |  3.3.1
| node                             |  18.7.0
| yarn                      |  1.22.17

**Comment by sgshy1995** [comment]
I just change the `index.d.ts` like this:

```typescript
type ToastContainerType = import("react-native-toast-notifications/lib/typescript/toast-container").ToastContainer;

declare global {
  const toast: ToastContainerType;
}

declare var toast: ToastContainerType;
```

then I can see the syntax prompt of `toast.show()` and the typescript error disappear too. Looks like everything is ok.

<img width="309" alt="image" src="https://user-images.githubusercontent.com/45568580/210936441-8ddddc89-3dc4-4e94-a189-5b434a952622.png">

So is there something wrong with your example [index.d.ts](https://github.com/arnnis/react-native-toast-notifications/blob/master/example/index.d.ts) or did I write something wrong ?

**Comment by genesisxyz** [comment]
You can keep the [index.d.ts](https://github.com/arnnis/react-native-toast-notifications/blob/master/example/index.d.ts) of the README but you need to add ! on the ref

```ts
ref={(ref) => {
    global["toast"] = ref!;
}}
```

Works with typescript 4.9.4, expo SDK 48

**Comment by arnnis** [comment]
Check the new global API introduced in [version 3.4.0](https://github.com/arnnis/react-native-toast-notifications/releases/tag/v3.4.0), It is easier to use and has better Typescript support.

([docs](https://github.com/arnnis/react-native-toast-notifications#--how-to-call-toast-outside-react-components))
