### ISSUE TITLE
Feat req: alert style

### ISSUE THREAD

**Issue by jamesholcomb** [arnnis/react-native-toast-notifications#84]
Similar to https://github.com/seniv/react-native-notifier

![image](https://user-images.githubusercontent.com/362729/127885640-c9da03ec-20f8-4a6a-b356-b77f8efceda9.png)

**Comment by arnnis** [comment]
You can achieve this by implementing  a custom toast type. 

![image](https://user-images.githubusercontent.com/61647712/127899373-a30a4d76-5494-47a4-8b6a-b0b31c7777e8.png)

```js
<ToastProvider
    placement="top"
    renderType={{
       system: (toast) => (
          <View
            style={{
              width: "100%",
              backgroundColor: "red",
              justifyContent: "center",
              alignItems: "center",
              paddingTop: 50,
              paddingBottom: 18,
            }}
          >
            <Text style={{ color: "#fff", fontWeight: "bold" }}>
              {toast.data.title}
            </Text>
            <Text style={{ color: "#fff", marginTop: 8 }}>{toast.message}</Text>
          </View>
       ) 
   }}
/>

```

The extra data, which in this case is `title`, can be passed using the data property. 

`toast.show("Check your connection", {data:{title: "Network unavaiable"}})`

This should work but for this use case we might need a prop to disable stacking. I'll add that to my todo.
