### ISSUE TITLE
toast was show underneath of Modal

### ISSUE THREAD

**Issue by louiskhenghao** [arnnis/react-native-toast-notifications#88]
### Current behaviour
If I have a modal the toast will be blocked by `Modal` in react-native-web.
I find out the z-index of toast was set to 999, and the default z-index for Modal was 9999.

### Expected behaviour

If there is a props allows customizing the z-index level that will be great.

### Code sample

For Syntax Highlighting check this [link](https://help.github.com/en/articles/creating-and-highlighting-code-blocks)

#### Toast z-index
![toast-zindex](https://user-images.githubusercontent.com/5268771/129783152-d5248046-6aee-4393-9fcf-94d9ad9942cb.png)

#### Modal z-index = 9999
![Screen Shot 2021-08-18 at 2 45 39 AM](https://user-images.githubusercontent.com/5268771/129783326-f5e775ab-f8d6-4368-bce1-566a0465b91e.png)

### What have you tried

Was thinking to overwrite the z-index with css, but since css class name is randomize so i couldn't target it.

### Your Environment

| software                         | version |
| -------------------------------- | ------- |
| chrome                  | 92.0.4515.131|
| react                    |17|
| react-native-toast-notifications |3.1.0
| node                             |14.16.1|
| npm                      |6.14.12|

**Comment by arnnis** [comment]
Thanks for detailed issue. [a patch](https://github.com/arnnis/react-native-toast-notifications/releases/tag/v3.1.1) is now released with 999999 for z-index.
