### ISSUE TITLE
Can't customize toast when calling toast outside react component 

### ISSUE THREAD

**Issue by uffou** [arnnis/react-native-toast-notifications#91]
I am using the example for the FAQ https://github.com/arnnis/react-native-toast-notifications#--how-to-call-toast-outside-react-components

And a provider with customization like for example `successColor: 'orange'` 

Calling `toast.show('test',{type:'success'})` works but does not take the customizations into account and I couldn't find another way to add these customizations.

**Comment by arnnis** [comment]
You don't need the `Provider` if not using hooks. instead you should customize `<Toast />` itself. 
```
<Toast successColor="orange" ref={ref => global["toast"] = ref} />
```
