### ISSUE TITLE
Can we get an option to disable swipe for Android? On Press hardly gets called

### ISSUE THREAD

**Issue by gabrielbezerra81** [arnnis/react-native-toast-notifications#92]
Hi, first of all thanks for this amazing library!

I had troubles trying to make onPress work with android. Instead of calling onPress it tries to swipe left or right.

**Comment by arnnis** [comment]
Hi. 
I just published a new release ([v3.2.0](https://github.com/arnnis/react-native-toast-notifications/releases/tag/v3.2.0)). 
We have  `swipeEnabled` prop to disable swipe now. It's suppose to be used both in `ToastProvider` or in `show()` for each single toast.
To disable swipe completely on android you can do this:
```
<ToastProvider swipeEnabled={Platfrom.OS !== "android"}>
...
```

**Comment by gabrielbezerra81** [comment]
Thank you very much! Amazing library.

**Comment by l2aelba** [comment]
@arnnis Can we improve this without `swipeEnabled: false` ?
