### ISSUE TITLE
not centering on landscape mode

### ISSUE THREAD

**Issue by radelcom** [arnnis/react-native-toast-notifications#95]
### Current behaviour
- when the device is rotated to landscape mode, the toast doesnt seem to center when shown.

- it render in the left side of the screen either top or bottom left.

### Expected behaviour
- should center in any orientation 

- should center in any orientation

**Comment by arnnis** [comment]
Thanks for reporting the issue, This should be fixed now in the latest patch [v3.2.2](https://github.com/arnnis/react-native-toast-notifications/releases/tag/v3.2.2)
