### ISSUE TITLE
Is there anyway to disable multiple toasts appearing one after the other?

### ISSUE THREAD

**Issue by aravi365** [arnnis/react-native-toast-notifications#96]
I have used the toast to display when the authToken gets expire. But when multiple apis are called, it shows multiple times. Is there any way to make sure that only one toast appears at a time?

**Comment by arnnis** [comment]
You should make sure your code is called only once because it's either stacking or queuing toast (like in android native toasts)
```
let logout ⇒ () ⇒ {
   if (isHandlingLogout) {
      return
   }
   isHadlingLogout = true
   toast.show(...)
}
```
You can also store the toast id in a global variable like this to check if it's already shown
```
let toastId = null
let logout => {
   if (toastId === null) {
      toastId = toast.show(...)
   }
}
```
