### ISSUE TITLE
EventEmitter.removeListener('change', ...) Method has been deprecated

### ISSUE THREAD

**Issue by danieltereschenko** [arnnis/react-native-toast-notifications#99]
"react-native": "0.65.1",
    "react-native-toast-notifications": "^3.2.2",
    
    I'm getting this warning on IOS (didn't test on android) after notifications dismissed
    
    
![image](https://user-images.githubusercontent.com/37038091/134306272-dbbac923-4910-452b-bf10-cd54399eea50.png)

**Comment by arnnis** [comment]
The warning is added to react-native 65, which has not yet been released by Expo. Since the example app is in expo, we'll update to the new API once expo is released.
For now, you can ignore warnings using the `LogBox.ignoreLogs()` api.

**Comment by arnnis** [comment]
This should be fixed in the latest patch [v3.2.3](https://github.com/arnnis/react-native-toast-notifications/releases/tag/v3.2.3)
